### ISSUE TITLE
FamilyInstance.ByGeometry

### ISSUE THREAD

**Issue by josols** [dimven/SpringNodes#17]
I've come across an issue when importing geometry to Revit. Don't know if bug or user error, The revit file is set in m and the family instance is all blank. Haven't got test files for the moment, but can produce if needed.

![image](https://cloud.githubusercontent.com/assets/7080648/18090889/0bca0566-6ec7-11e6-91fc-6bf8d2a67315.png)

**Comment by josols** [comment]
Additionally, if I run again, sometimes I get an error message stating something in the vicinity of: File "<string>", line 86, in New Form etc etc.. AttributeError: "NoneType" object has no scale etc etc..

**Comment by taurerm** [comment]
Similar issue here - FamilyInstance.ByGeometry fails on the geometry that results by cutting a cuboid with a topo... 
![capture](https://cloud.githubusercontent.com/assets/3396098/19221376/898cb094-8e42-11e6-9011-b92faaac16bd.png)

DirectShape.ByGeometry works and then I can convert the Direct Shape with FamilyInstance.ByGeometry in a second Dynamo....

**Comment by dimven** [comment]
I think we looked into this with @josols and the issue was that the filepath node was outputting a wrong path for the template?

@taurerm if feeding the path as a string (using the string node) doesn't help, could you share the resulting geometry or an image of it? It might be that it's simply too much to handle for the SAT export/import. The builtin directshape node uses the tessellatedshapebuilder that both heavily triangulates the object and tries to fix any inconsistencies in the shape, like microscopic gaps or overlaps.

**Comment by taurerm** [comment]
Hi Dimitar

The FilePath node was the issue - feeding the template name as a string
worked perfectly.

Thanks for the tip
Martin

Martin Taurer
taurerm@gmail.com
+31 6 34489 403

**Comment by dimven** [comment]
No problem. Apparently this is fixed in Dynamo 1.2

**Comment by taurerm** [comment]
Hi Dimitar

It's still present in 1.2.0.2690...

Cheers
Martin

Martin Taurer
taurerm@gmail.com
+31 6 34489 403

**Comment by andydandy74** [comment]
That's weird. This should be fixed in 1.2 stable. Did your filepath contain any special characters besides whitespace (e.g. Umlaute), Martin?

**Comment by taurerm** [comment]
No - and that is the weirdness... I have attached two graphs, in one I need
to use the string node to make it work, in the second one the file path
node works...[image: Inline image 1][image: Inline image 2]
Thanks for looking into this
Martin

Martin Taurer
taurerm@gmail.com
+31 6 34489 403
